CREATE TABLE answers (
  _id BIGSERIAL PRIMARY KEY,
  authorId BIGINT REFERENCES users(_id) ON DELETE CASCADE NOT NULL,
  questionId BIGINT REFERENCES questions(_id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);