CREATE TABLE questions (
  _id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  authorId INT REFERENCES users(_id) ON DELETE CASCADE NOT NULL,
  views INT DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);